version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pdadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - "5050:80"
  mysql:
    image: mysql:5
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postgres
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    ports:
      - "9000:80"

# sudo docker-compose up -d
# sudo docker-compose up -d pdadmin
# sudo docker-compose exec postgres psql -U postgres
# sudo docker-compose exec postgres bash
# psql -h localhost -d postgres -U postgres -p 5432
# sudo docker inspect b9a5960705a9 | grep IPAddress
# sudo docker exec -it mysql mysql -u root -p
# CREATE USER 'postgres'@'%' IDENTIFIED BY 'postgres';
# Query OK, 0 rows affected (0.00 sec)

# mysql> GRANT ALL PRIVILEGES ON *.* TO 'postgres'@'%' WITH GRANT OPTION;
# Query OK, 0 rows affected (0.00 sec)

# mysql> FLUSH PRIVILEGES;
# Query OK, 0 rows affected (0.00 sec)
